# -*- coding: utf-8 -*-
"""Python_finance_project7.ipynb_day4_pandas_calculating_returns_of_stock_and_showing_in_graph

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VxLPqBVEpVFPEjU_BqMQZ0llTcVyI9Wl
"""

# Commented out IPython magic to ensure Python compatibility.
# # The %%capture supresses pip install message.
# %%capture
# !pip install yfinance, numpy, pandas, Matplotlib
#

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import yfinance as yf

data1 = pd.read_csv('/content/AAPL[1].csv') #Data downloaded from Kaggle for APPLE
data1.head()

print(data1.columns)

len(data1['Open'])

data2 = pd.read_csv('/content/MSFT_1986-03-13_2025-02-04[1].csv') #For Microsoft
data2.head()

data3 = pd.read_csv('/content/TSLA[1].csv')   #For Tesla

# Plottng linear graphs of stock_price relationship to time in days for APPlE, MICROSOFT, and TESLA
x = list(range(0, len(data1)))
y = list(data1['Close'])
a = list(range(0,len(data2)))
b = list(data2['Close'])
c = list(range(0, len(data3)))
d = list(data3['Close'])

plt.plot(c,d, label='TSLA')
plt.plot(a,b, label='MSFT')
plt.plot(x,y, label='AAPL')

plt.xlabel('Days')
plt.ylabel('Close_Price')
plt.title("Stock Prices of AAPL, MSFT, and TSLA")
plt.legend()

data2 = pd.read_csv('/content/MSFT_1986-03-13_2025-02-04[1].csv')
data2.head()

#Downloading data from Yahoo Finance from last five years as today

from datetime import datetime, timedelta
import yfinance as yf

today = datetime.now()
five_years_ago = today - timedelta(days=5*365) #Time delta helps to find time difference between times.

tsla_data = yf.download('TSLA', start=five_years_ago.strftime('%Y-%m-%d'), end=today.strftime('%Y-%m-%d'))
print(tsla_data.head())

print(tsla_data.columns)

import yfinance as yf
from datetime import datetime, timedelta

# Calculate the date 5 years ago from today
today = datetime.now()
five_years_ago = today - timedelta(days=5*365)

# Download TSLA stock data for the last 5 years
msft_data = yf.download('MSFT', start=five_years_ago.strftime('%Y-%m-%d'), end=today.strftime('%Y-%m-%d'))

# Save the data to a CSV file
msft_data.to_csv('MSFT_last_5_years.csv')

# Display the first 5 rows of the downloaded data
display(msft_data.tail())
msft_x = msft_data.index
msft_y = list(msft_data[('Close', 'MSFT')])
plt.plot(msft_x, msft_y)
plt.xlabel('Date')
plt.ylabel('Close Price')
plt.title('MSFT Stock Close Price (Last 5 Years)')
plt.show()

import yfinance as yf
from datetime import datetime, timedelta
import matplotlib.pyplot as plt


today = datetime.now()
five_years_ago = today - timedelta(days=5*365)


tsla_data = yf.download('TSLA', start=five_years_ago.strftime('%Y-%m-%d'), end=today.strftime('%Y-%m-%d'))
msft_data = yf.download('MSFT', start=five_years_ago.strftime('%Y-%m-%d'), end=today.strftime('%Y-%m-%d'))
aapl_data = yf.download('AAPL', start=five_years_ago.strftime('%Y-%m-%d'), end=today.strftime('%Y-%m-%d'))


tsla_data.to_csv('TSLA_last_5_years.csv')
msft_data.to_csv('MSFT_last_5_years.csv')
aapl_data.to_csv('AAPL_last_5_years.csv')


print("TSLA Data Tail:")
display(tsla_data.tail())
print("MSFT Data Tail:")
display(msft_data.tail())
print("AAPL Data Tail:")
display(aapl_data.tail())


plt.figure(figsize=(12, 6))

plt.plot(tsla_data.index, tsla_data[('Close', 'TSLA')], label='TSLA')
plt.plot(msft_data.index, msft_data[('Close', 'MSFT')], label='MSFT')
plt.plot(aapl_data.index, aapl_data[('Close', 'AAPL')], label='AAPL')

plt.xlabel('Date')
plt.ylabel('Close Price')
plt.title('Stock Close Prices (TSLA, MSFT, AAPL) - Last 5 Years')
plt.legend()
plt.grid(True)
plt.show()

print(tsla_data.columns)
print(aapl_data.columns)
print(msft_data.columns)

# Calculate daily returns using pct_change()
aapl_returns = aapl_data[('Close', 'AAPL')].pct_change()
msft_returns = msft_data[('Close', 'MSFT')].pct_change()
tsla_returns = tsla_data[('Close', 'TSLA')].pct_change()

# Plot histograms for daily returns
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.hist(aapl_returns.dropna(), bins=50, color='skyblue', edgecolor='black')
plt.title('AAPL Daily Returns Histogram')
plt.xlabel('Daily Return')
plt.ylabel('Frequency')

plt.subplot(1, 3, 2)
plt.hist(msft_returns.dropna(), bins=50, color='lightgreen', edgecolor='black')
plt.title('MSFT Daily Returns Histogram')
plt.xlabel('Daily Return')
plt.ylabel('Frequency')

plt.subplot(1, 3, 3)
plt.hist(tsla_returns.dropna(), bins=50, color='salmon', edgecolor='black')
plt.title('TSLA Daily Returns Histogram')
plt.xlabel('Daily Return')
plt.ylabel('Frequency')

plt.tight_layout() # Adjust layout to prevent overlap
plt.show()