# -*- coding: utf-8 -*-
"""Python_finance_project7.ipynb_day1_numpy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r6C3YBa347r2c3S3aWAcXr9PhAsO5OXD

**Day 1: Excercise 1**
"""

pip install numpy

import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])

print(array1 + array2)

print(array1 - array2)

print(array1 * array2)

"""**Day 1: Excercise 2**"""

array3 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(array3)

print(array3.shape)

print(array3 * 2)

sum_of_rows = np.sum(array3, axis = 1)
print(sum_of_rows)
print(np.max(sum_of_rows))

"""**Day 1: Excercise 3**"""

x = np.random.randn(100)
print(x)

print(np.mean(x))

print(np.min(x))

print(np.std(x))

"""**Day 1: Excercise 4**"""

y = np.random.randint(low = 50, high = 100, size = 1000)
print(y)

A_students = np.where(y>=90)
print(A_students)
Number_of_A_student = np.count_nonzero(A_students)
print(f"The number of students who received an A in the school were {Number_of_A_student/10} %.")

B_students = np.where((y>=80) & (y<90))
Number_of_B_student = np.count_nonzero(B_students)
print(f"The number of students who received a B in the school were {Number_of_B_student/10} %.")

C_students = np.where((y>=70) & (y<80))
print(C_students)
Number_of_C_student = np.count_nonzero(C_students)
print(f"The number of students who received a C in the school were {Number_of_C_student/10} %.")

F_students = np.where(y < 70)
print(F_students)
print(np.count_nonzero(F_students))
Number_of_F_student = np.count_nonzero(F_students)
print(f"The number of students who received a C in the school were {Number_of_F_student/10} %.")

