# -*- coding: utf-8 -*-
"""Python_finance_project7.ipynb_day2_pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vfsenHQZ2mo6AjJpZCCG4F38a0ckndEn

**Day 2: Excercie 1**
"""

pip install numpy

import numpy as np

pip install pandas

import pandas as pd

Student_and_their_grades = {
    "Name": ["Frank", "John", "Anna", "Leo"],
    "Math_Score": [90, 91, 40, 93],
    "Science_score": [95, 97, 96, 92]
}

df = pd.DataFrame(Student_and_their_grades)

print(df)

y = Student_and_their_grades['Math_Score']
print(y)
print(np.max(y))
print(np.sort(y))

z = Student_and_their_grades['Science_score']
print(z)
print(np.max(z))
print(np.sort(z))

df["Total_score"] = df['Math_Score'] + df['Science_score']
df["Passed"] = df["Total_score"] >= 150
print(df)

df.to_excel('grades.xlsx', index=False)
print("DataFrame saved to grades.xlsx")

df.to_csv('sample_data/Yash_grade.csv', index=False)
print("DataFrame saved to sample_data/Yash_grade.csv")

df.to_csv('sample_data/Yash_grade.csv', index=False)
print(df)

df3 = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

len(df3)
df3

np.sum(df3['PassengerId'])

df4 = df3.dropna()
df4

np.average(df4['Age'])

survivors_df = df4[df4['Survived'] == 1]
survivors_df
print(np.average(survivors_df['Fare']))

nonsurvivors_df = df4[df4['Survived'] == 0]
nonsurvivors_df
print(np.average(nonsurvivors_df['Fare']))